checking response from gateway before connecting since if gateway is down, the attempt to connect will just stall before failing

diff --git a/alliance b/alliance
--- a/alliance
+++ b/alliance
@@ -1,12 +1,20 @@
 #!/bin/sh
 
+## lock file path
+LOCK_FILE=/tmp/.alliance.pid
+
 ## read encrypted data set
 export $(gpg --decrypt /etc/conf.d/alliance.data.asc 2>/dev/null)
 
-## functions
+
+
+##------------------------------------------------------------------------------
+## start of functions
+##------------------------------------------------------------------------------
+
 iface_up () {
     if (( UID != 0 )); then
-        echo "error: you cannot perform this operation unless you are root."
+        echo "error: you cannot perform this operation unless you are root." 1>&2
     else
         iface_down
 
@@ -27,21 +35,26 @@ iface_down () {
 
 all_login () {
     if (( UID == 0 )); then
-        echo "error: you cannot perform this operation as root."
+        echo "error: you cannot perform this operation as root." 1>&2
     else
-        curl -s --cookie cjar  --data "user=$ALLIANCE_USERNAME" \
-            --data "pass=$ALLIANCE_PASSWORD" \
-            --data 'login=Login' $ALLIANCE_LOGIN_PAGE >/dev/null
+        gateway_response
+        if (( $? == 1 )); then
+            curl -s --cookie cjar  --data "user=$ALLIANCE_USERNAME" \
+                --data "pass=$ALLIANCE_PASSWORD" \
+                --data 'login=Login' $ALLIANCE_LOGIN_PAGE >/dev/null
 
-        user_agent="Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.2.3)"\
-" Gecko/20100401 Firefox/3.6.3"
-        ip=$(curl -sA $user_agent http://whatismyipaddress.com/ | \
-            grep "LOOKUPADDRESS" | \
-            sed 's/.*value="\([0-9.]*\).*/\1/')
-        if [[ -z $ip ]]; then
-            echo "error connecting to network"
+            local user_agent="Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3"
+
+            local ip=$(curl -sA $user_agent http://whatismyipaddress.com/ | \
+                grep "LOOKUPADDRESS" | \
+                sed 's/.*value="\([0-9.]*\).*/\1/')
+            if [[ -z $ip ]]; then
+                echo "error connecting to network" 1>&2
+            else
+                echo "IP :: $ip"
+            fi
         else
-            echo "IP :: $ip"
+            echo "error: no response from gateway :: ${ALLIANCE_GATEWAY}"
         fi
     fi
 }
@@ -55,23 +68,32 @@ all_logout () {
 }
 
 all_expiry () {
-    expiry=$(curl -s http://10.13.1.1/0/up/ | \
+    local expiry=$(curl -s http://10.13.1.1/0/up/ | \
         grep "Expiry date" | \
         sed -re 's/.*left">([0-9.]*)<span.*/\1/' \
         -e 's/([0-9]*).([0-9]*).([0-9]*)/\2\/\1\/\3/')
+
     if [[ -z $expiry ]]; then
-        echo "error connecting to network"
+        echo "error connecting to network" 1>&2
     else
-        expiry_date=$(date --date "$expiry" +"%d-%b-%Y")
+        local expiry_date=$(date --date "$expiry" +"%d-%b-%Y")
         echo "Subscription expires on :: $expiry_date"
     fi
 }
 
+
+gateway_response () {
+    local ping_response=$(ping -c1 $ALLIANCE_GATEWAY | grep "1 received" -c)
+    return $ping_response
+}
+
+
+
 usage () {
     cat <<EOF
-Usage:   $(basename $0) [options]
+    Usage:   $(basename $0) [options]
 
- Basic options:
+    Basic options:
     -s        setup network connection
     -l        login to alliance network [default]
     -x        logout from alliance network
@@ -80,38 +102,56 @@ Usage:   $(basename $0) [options]
 EOF
 }
 
+error_exit () {
+    usage
+    rm "$LOCK_FILE"
+    exit 1
+}
 
-## main execution
-while getopts ":sxleh" opt; do
-    case $opt in
-        s)
-            iface_up
-            ;;
-        x)
-            all_logout
-            ;;
-        l)
-            all_login
-            ;;
-        e)
-            all_expiry
-            ;;
-        h)
-            usage
-            ;;
-        \?)
-            echo "invalid option: -$OPTARG" >&2
-            usage
-            exit 1
-            ;;
-        :)
-            echo "Option -$OPTARG requires an argument." >&2
-            usage
-            exit 1
-            ;;
-    esac
-done
+##------------------------------------------------------------------------------
+## end of functions
+##------------------------------------------------------------------------------
 
-if (( $# == 0 )); then
-    all_login
+if [[ -e "$LOCK_FILE" ]]; then
+    echo "another instance is still active ... $(<$LOCK_FILE)" 1>&2
+    echo "if you are sure another instance is not up, you can remove ${LOCK_FILE}"
+else
+    # creating the lock file
+    echo "$$" > "$LOCK_FILE"
+
+    # main execution
+    while getopts ":sxleh" opt; do
+        case $opt in
+            s)
+                iface_up
+                ;;
+            x)
+                all_logout
+                ;;
+            l)
+                all_login
+                ;;
+            e)
+                all_expiry
+                ;;
+            h)
+                usage
+                ;;
+            \?)
+                echo "invalid option: -$OPTARG" >&2
+                error_exit
+                ;;
+            :)
+                echo "Option -$OPTARG requires an argument." >&2
+                error_exit
+                ;;
+        esac
+    done
+
+    if (( $# == 0 )); then
+        all_login
+    fi
+
+    ## removing lock
+    rm "$LOCK_FILE"
 fi
